import type { Metadata } from "next";
import { ReactNode } from "react";

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type LayoutProps = {
    children: ReactNode;
};
const AuthLayout = ({ children }: LayoutProps) => {
    return (        
            <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
                {children}
            </div>
    );
};

export { metadata };
export default AuthLayout;


